In [ ]:
Dict = {'https://www.globalfirepower.com/total-population-by-country.php': 'total_population',
        'https://www.globalfirepower.com/available-military-manpower.php': 'total_military_manpower',
        'https://www.globalfirepower.com/manpower-fit-for-military-service.php': 'fit_for_service',
        'https://www.globalfirepower.com/manpower-reaching-military-age-annually.php': 'population_reaching_military_age_annually',
        'https://www.globalfirepower.com/active-military-manpower.php': 'active_personnel',
        'https://www.globalfirepower.com/active-reserve-military-manpower.php': 'reserve_personnel',
        'https://www.globalfirepower.com/manpower-paramilitary.php': 'paramilitary',
        'https://www.globalfirepower.com/aircraft-total.php': 'total_military_aircraft',
        'https://www.globalfirepower.com/aircraft-total-fighters.php': 'fighter_aircraft',
        'https://www.globalfirepower.com/aircraft-total-attack-types.php': 'attack_aircraft',
        'https://www.globalfirepower.com/aircraft-total-transports.php': 'transport_aircraft',
        'https://www.globalfirepower.com/aircraft-total-trainers.php': 'trainer_aircraft',
        'https://www.globalfirepower.com/aircraft-total-special-mission.php': 'special_mission_aircraft',
        'https://www.globalfirepower.com/aircraft-total-tanker-fleet.php': 'tanker_aircraft',
        'https://www.globalfirepower.com/aircraft-helicopters-total.php': 'total_military_helicopters',
        'https://www.globalfirepower.com/aircraft-helicopters-attack.php': 'attack_helicopters',
        'https://www.globalfirepower.com/armor-tanks-total.php': 'tanks',
        'https://www.globalfirepower.com/armor-apc-total.php': 'armored_fighting_vehicles',
        'https://www.globalfirepower.com/armor-self-propelled-guns-total.php': 'self_propelled_artillery',
        'https://www.globalfirepower.com/armor-towed-artillery-total.php': 'towed_artillery',
        'https://www.globalfirepower.com/armor-mlrs-total.php': 'rocket_projectors',
        'https://www.globalfirepower.com/navy-ships.php': 'total_naval_fleet',
        'https://www.globalfirepower.com/navy-force-by-tonnage.php': 'total_naval_fleet_tonnage_mt',
        'https://www.globalfirepower.com/navy-aircraft-carriers.php': 'aircraft_carriers',
        'https://www.globalfirepower.com/navy-helo-carriers.php': 'helicopter_carriers',
        'https://www.globalfirepower.com/navy-submarines.php': 'submarines',
        'https://www.globalfirepower.com/navy-destroyers.php': 'destroyers',
        'https://www.globalfirepower.com/navy-frigates.php': 'frigates',
        'https://www.globalfirepower.com/navy-corvettes.php': 'corvettes',
        'https://www.globalfirepower.com/navy-patrol-coastal-craft.php': 'coastal_patrol_craft',
        'https://www.globalfirepower.com/navy-mine-warfare-craft.php': 'mine_warfare_craft',
        'https://www.globalfirepower.com/defense-spending-budget.php': 'defense_budget_usd',
        'https://www.globalfirepower.com/external-debt-by-country.php': 'external_debt_usd',
        'https://www.globalfirepower.com/purchasing-power-parity.php': 'purchasing_power_parity_usd',
        'https://www.globalfirepower.com/reserves-of-foreign-exchange-and-gold.php': 'foreign_exchange_and_gold_reserves_usd',
        'https://www.globalfirepower.com/major-serviceable-airports-by-country.php': 'total_serviceable_airports',
        'https://www.globalfirepower.com/labor-force-by-country.php': 'labour_force',
        'https://www.globalfirepower.com/major-ports-and-terminals.php': 'major_ports_and_terminals',
        'https://www.globalfirepower.com/merchant-marine-strength-by-country.php': 'total_merchant_marine_fleet',
        'https://www.globalfirepower.com/railway-coverage.php': 'railway_coverage_km',
        'https://www.globalfirepower.com/roadway-coverage.php': 'roadway_coverage_km',
        'https://www.globalfirepower.com/oil-production-by-country.php': 'oil_production_bbl',
        'https://www.globalfirepower.com/oil-consumption-by-country.php': 'oil_consumption_bbl',
        'https://www.globalfirepower.com/proven-oil-reserves-by-country.php': 'proven_oil_reserves_bbl',
        'https://www.globalfirepower.com/natural-gas-production-by-country.php': 'natural_gas_production_cum',
        'https://www.globalfirepower.com/natural-gas-consumption-by-country.php': 'natural_gas_consumption_cum',
        'https://www.globalfirepower.com/proven-natural-gas-reserves-by-country.php': 'proven_natural_gas_reserves_cum',
        'https://www.globalfirepower.com/coal-production-by-country.php': 'coal_production_cum',
        'https://www.globalfirepower.com/coal-consumption-by-country.php': 'coal_consumption_mt',
        'https://www.globalfirepower.com/proven-coal-reserves-by-country.php': 'proven_coal_reserves_cum',
        'https://www.globalfirepower.com/square-land-area.php': 'total_land_area_sq_km',
        'https://www.globalfirepower.com/coastline-coverage.php': 'coastline_coverage_km',
        'https://www.globalfirepower.com/border-coverage.php': 'border_coverage_km',
        'https://www.globalfirepower.com/waterway-coverage.php': 'waterway_coverage_km'
    }

In [ ]:
url=[]
names=[]
for link,name in Dict.items():
    url.append(link)
    names.append(name)

In [ ]:
import requests
from bs4 import BeautifulSoup
import re

In [ ]:
final_result=[]
for link,name in Dict.items():
    u=link
    response=requests.get(u)
    soup = BeautifulSoup(response.text, 'html.parser')
    all_links=soup.find_all('a')
    specific_urls=[]
    for link in all_links:
        href = link.get("href")
        if "country_id" in href:
            specific_urls.append(link)

    for record in specific_urls:
        country_div = record.find("div", class_="longFormName")
        value_div = record.find("div", class_="valueContainer")

        if not country_div or not value_div:
            continue

        country = country_div.text.strip()
        value = value_div.text.strip()
        regex = "[^0-9]"
        value=(re.sub(regex, "", value))

        final_result.append({
            "country": country,
            "metric": name,
            "value": int(value)
        })

In [ ]:
print(final_result)

[{'country': 'China', 'metric': 'total_population', 'value': 1415043270}, {'country': 'India', 'metric': 'total_population', 'value': 1409128296}, {'country': 'United States', 'metric': 'total_population', 'value': 341963408}, {'country': 'Indonesia', 'metric': 'total_population', 'value': 281562465}, {'country': 'Pakistan', 'metric': 'total_population', 'value': 252363571}, {'country': 'Nigeria', 'metric': 'total_population', 'value': 236747130}, {'country': 'Brazil', 'metric': 'total_population', 'value': 220051512}, {'country': 'Bangladesh', 'metric': 'total_population', 'value': 168697184}, {'country': 'Russia', 'metric': 'total_population', 'value': 140820810}, {'country': 'Mexico', 'metric': 'total_population', 'value': 130739927}, {'country': 'Japan', 'metric': 'total_population', 'value': 123201945}, {'country': 'Ethiopia', 'metric': 'total_population', 'value': 118550298}, {'country': 'Philippines', 'metric': 'total_population', 'value': 118277063}, {'country': 'Democratic Republic of the Congo', 'metric': 'total_population', 'value': 115403027}, {'country': 'Egypt', 'metric': 'total_population', 'value': 111247248}, {'country': 'Vietnam', 'metric': 'total_population', 'value': 105758975}, {'country': 'Iran', 'metric': 'total_population', 'value': 88386937}, {'country': 'Turkiye', 'metric': 'total_population', 'value': 84119531}, {'country': 'Germany', 'metric': 'total_population', 'value': 84119100}, {'country': 'Thailand', 'metric': 'total_population', 'value': 69920998}, {'country': 'United Kingdom', 'metric': 'total_population', 'value': 68459055}, {'country': 'France', 'metric': 'total_population', 'value': 68374591}, {'country': 'Tanzania', 'metric': 'total_population', 'value': 67462121}, {'country': 'Italy', 'metric': 'total_population', 'value': 60964931}, {'country': 'South Africa', 'metric': 'total_population', 'value': 60442647}, {'country': 'Kenya', 'metric': 'total_population', 'value': 58246378}, {'country': 'Myanmar', 'metric': 'total_population', 'value': 57527139}, {'country': 'South Korea', 'metric': 'total_population', 'value': 52081799}, {'country': 'Sudan', 'metric': 'total_population', 'value': 50467278}, {'country': 'Colombia', 'metric': 'total_population', 'value': 49588357}, {'country': 'Uganda', 'metric': 'total_population', 'value': 49283041}, {'country': 'Spain', 'metric': 'total_population', 'value': 47280433}, {'country': 'Algeria', 'metric': 'total_population', 'value': 47022473}, {'country': 'Argentina', 'metric': 'total_population', 'value': 46994384}, {'country': 'Iraq', 'metric': 'total_population', 'value': 42083436}, {'country': 'Afghanistan', 'metric': 'total_population', 'value': 40121552}, {'country': 'Canada', 'metric': 'total_population', 'value': 38794813}, {'country': 'Poland', 'metric': 'total_population', 'value': 38746310}, {'country': 'Morocco', 'metric': 'total_population', 'value': 37387585}, {'country': 'Angola', 'metric': 'total_population', 'value': 37202061}, {'country': 'Saudi Arabia', 'metric': 'total_population', 'value': 36544431}, {'country': 'Uzbekistan', 'metric': 'total_population', 'value': 36520593}, {'country': 'Ukraine', 'metric': 'total_population', 'value': 35661826}, {'country': 'Ghana', 'metric': 'total_population', 'value': 34589092}, {'country': 'Malaysia', 'metric': 'total_population', 'value': 34564810}, {'country': 'Mozambique', 'metric': 'total_population', 'value': 33350954}, {'country': 'Peru', 'metric': 'total_population', 'value': 32600249}, {'country': 'Yemen', 'metric': 'total_population', 'value': 32140443}, {'country': 'Venezuela', 'metric': 'total_population', 'value': 31250306}, {'country': 'Nepal', 'metric': 'total_population', 'value': 31122387}, {'country': 'Cameroon', 'metric': 'total_population', 'value': 30966105}, {'country': 'Ivory Coast', 'metric': 'total_population', 'value': 29981758}, {'country': 'Madagascar', 'metric': 'total_population', 'value': 29452714}, {'country': 'Australia', 'metric': 'total_population', 'value': 26768598}, {'country': 'Niger', 'metric': 'total_population', 'value': 26342784}, {'country': 'North Korea', 'metric': 'total_population', 'value': 26298666}, {'country': 'Syria', 'metric': 'total_population', 'value': 23865423}, {'country': 'Taiwan', 'metric': 'total_population', 'value': 23595274}, {'country': 'Burkina Faso', 'metric': 'total_population', 'value': 23042199}, {'country': 'Mali', 'metric': 'total_population', 'value': 21990607}, {'country': 'Sri Lanka', 'metric': 'total_population', 'value': 21982608}, {'country': 'Zambia', 'metric': 'total_population', 'value': 20799116}, {'country': 'Kazakhstan', 'metric': 'total_population', 'value': 20260006}, {'country': 'Chad', 'metric': 'total_population', 'value': 19093595}, {'country': 'Senegal', 'metric': 'total_population', 'value': 18847519}, {'country': 'Chile', 'metric': 'total_population', 'value': 18664652}, {'country': 'Ecuador', 'metric': 'total_population', 'value': 18309984}, {'country': 'Guatemala', 'metric': 'total_population', 'value': 18255216}, {'country': 'Romania', 'metric': 'total_population', 'value': 18148155}, {'country': 'Netherlands', 'metric': 'total_population', 'value': 17772378}, {'country': 'Zimbabwe', 'metric': 'total_population', 'value': 17150352}, {'country': 'Cambodia', 'metric': 'total_population', 'value': 17063669}, {'country': 'Benin', 'metric': 'total_population', 'value': 14697052}, {'country': 'Somalia', 'metric': 'total_population', 'value': 13017273}, {'country': 'South Sudan', 'metric': 'total_population', 'value': 12703714}, {'country': 'Bolivia', 'metric': 'total_population', 'value': 12311974}, {'country': 'Tunisia', 'metric': 'total_population', 'value': 12048847}, {'country': 'Belgium', 'metric': 'total_population', 'value': 11977634}, {'country': 'Jordan', 'metric': 'total_population', 'value': 11174024}, {'country': 'Cuba', 'metric': 'total_population', 'value': 10966038}, {'country': 'Czechia', 'metric': 'total_population', 'value': 10837890}, {'country': 'Dominican Republic', 'metric': 'total_population', 'value': 10815857}, {'country': 'Azerbaijan', 'metric': 'total_population', 'value': 10650239}, {'country': 'Portugal', 'metric': 'total_population', 'value': 10639726}, {'country': 'Sweden', 'metric': 'total_population', 'value': 10589835}, {'country': 'Greece', 'metric': 'total_population', 'value': 10461091}, {'country': 'Tajikistan', 'metric': 'total_population', 'value': 10394063}, {'country': 'United Arab Emirates', 'metric': 'total_population', 'value': 10032213}, {'country': 'Hungary', 'metric': 'total_population', 'value': 9855745}, {'country': 'Honduras', 'metric': 'total_population', 'value': 9529188}, {'country': 'Belarus', 'metric': 'total_population', 'value': 9501451}, {'country': 'Israel', 'metric': 'total_population', 'value': 9402617}, {'country': 'Sierra Leone', 'metric': 'total_population', 'value': 9121049}, {'country': 'Austria', 'metric': 'total_population', 'value': 8967982}, {'country': 'Switzerland', 'metric': 'total_population', 'value': 8860574}, {'country': 'Laos', 'metric': 'total_population', 'value': 7953556}, {'country': 'Paraguay', 'metric': 'total_population', 'value': 7522549}, {'country': 'Libya', 'metric': 'total_population', 'value': 7361263}, {'country': 'Bulgaria', 'metric': 'total_population', 'value': 6782659}, {'country': 'Nicaragua', 'metric': 'total_population', 'value': 6676948}, {'country': 'Serbia', 'metric': 'total_population', 'value': 6652212}, {'country': 'El Salvador', 'metric': 'total_population', 'value': 6628702}, {'country': 'Eritrea', 'metric': 'total_population', 'value': 6343956}, {'country': 'Kyrgyzstan', 'metric': 'total_population', 'value': 6172101}, {'country': 'Republic of the Congo', 'metric': 'total_population', 'value': 6097665}, {'country': 'Singapore', 'metric': 'total_population', 'value': 6028459}, {'country': 'Denmark', 'metric': 'total_population', 'value': 5973136}, {'country': 'Turkmenistan', 'metric': 'total_population', 'value': 5744151}, {'country': 'Central African Republic', 'metric': 'total_population', 'value': 5650957}, {'country': 'Finland', 'metric': 'total_population', 'value': 5626414}, {'country': 'Slovakia', 'metric': 'total_population', 'value': 5563649}, {'country': 'Norway', 'metric': 'total_population', 'value': 5509733}, {'country': 'Liberia', 'metric': 'total_population', 'value': 5437249}, {'country': 'Lebanon', 'metric': 'total_population', 'value': 5364482}, {'country': 'Ireland', 'metric': 'total_population', 'value': 5233461}, {'country': 'New Zealand', 'metric': 'total_population', 'value': 5161211}, {'country': 'Georgia', 'metric': 'total_population', 'value': 4900961}, {'country': 'Panama', 'metric': 'total_population', 'value': 4470241}, {'country': 'Mauritania', 'metric': 'total_population', 'value': 4328040}, {'country': 'Croatia', 'metric': 'total_population', 'value': 4150116}, {'country': 'Oman', 'metric': 'total_population', 'value': 3901992}, {'country': 'Bosnia and Herzegovina', 'metric': 'total_population', 'value': 3798671}, {'country': 'Moldova', 'metric': 'total_population', 'value': 3599528}, {'country': 'Uruguay', 'metric': 'total_population', 'value': 3425330}, {'country': 'Mongolia', 'metric': 'total_population', 'value': 3281676}, {'country': 'Kuwait', 'metric': 'total_population', 'value': 3138355}, {'country': 'Albania', 'metric': 'total_population', 'value': 3107100}, {'country': 'Armenia', 'metric': 'total_population', 'value': 2976765}, {'country': 'Namibia', 'metric': 'total_population', 'value': 2803660}, {'country': 'Lithuania', 'metric': 'total_population', 'value': 2628186}, {'country': 'Qatar', 'metric': 'total_population', 'value': 2552088}, {'country': 'Gabon', 'metric': 'total_population', 'value': 2455105}, {'country': 'Botswana', 'metric': 'total_population', 'value': 2450668}, {'country': 'North Macedonia', 'metric': 'total_population', 'value': 2135622}, {'country': 'Slovenia', 'metric': 'total_population', 'value': 2097893}, {'country': 'Kosovo', 'metric': 'total_population', 'value': 1977093}, {'country': 'Latvia', 'metric': 'total_population', 'value': 1801246}, {'country': 'Bahrain', 'metric': 'total_population', 'value': 1566888}, {'country': 'Estonia', 'metric': 'total_population', 'value': 1193791}, {'country': 'Bhutan', 'metric': 'total_population', 'value': 884546}, {'country': 'Luxembourg', 'metric': 'total_population', 'value': 671254}, {'country': 'Suriname', 'metric': 'total_population', 'value': 646758}, {'country': 'Montenegro', 'metric': 'total_population', 'value': 599849}, {'country': 'Beliz', 'metric': 'total_population', 'value': 415789}, {'country': 'Iceland', 'metric': 'total_population', 'value': 364036}, {'country': 'China', 'metric': 'total_military_manpower', 'value': 764123366}, {'country': 'India', 'metric': 'total_military_manpower', 'value': 662290299}, {'country': 'United States', 'metric': 'total_military_manpower', 'value': 150463900}, {'country': 'Indonesia', 'metric': 'total_military_manpower', 'value': 137965608}, {'country': 'Nigeria', 'metric': 'total_military_manpower', 'value': 125475979}, {'country': 'Brazil', 'metric': 'total_military_manpower', 'value': 112226271}, {'country': 'Pakistan', 'metric': 'total_military_manpower', 'value': 108516336}, {'country': 'Bangladesh', 'metric': 'total_military_manpower', 'value': 82661620}, {'country': 'Russia', 'metric': 'total_military_manpower', 'value': 69002197}, {'country': 'Mexico', 'metric': 'total_military_manpower', 'value': 61447766}, {'country': 'Ethiopia', 'metric': 'total_military_manpower', 'value': 56904143}, {'country': 'Vietnam', 'metric': 'total_military_manpower', 'value': 54994667}, {'country': 'Japan', 'metric': 'total_military_manpower', 'value': 52976836}, {'country': 'Philippines', 'metric': 'total_military_manpower', 'value': 50859137}, {'country': 'Iran', 'metric': 'total_military_manpower', 'value': 49496685}, {'country': 'Egypt', 'metric': 'total_military_manpower', 'value': 45611372}, {'country': 'Turkiye', 'metric': 'total_military_manpower', 'value': 42985080}, {'country': 'Democratic Republic of the Congo', 'metric': 'total_military_manpower', 'value': 39237029}, {'country': 'Germany', 'metric': 'total_military_manpower', 'value': 38694786}, {'country': 'Thailand', 'metric': 'total_military_manpower', 'value': 36358919}, {'country': 'United Kingdom', 'metric': 'total_military_manpower', 'value': 31491165}, {'country': 'Myanmar', 'metric': 'total_military_manpower', 'value': 30489384}, {'country': 'France', 'metric': 'total_military_manpower', 'value': 30084820}, {'country': 'South Africa', 'metric': 'total_military_manpower', 'value': 27803618}, {'country': 'Italy', 'metric': 'total_military_manpower', 'value': 27434219}, {'country': 'Sudan', 'metric': 'total_military_manpower', 'value': 26747657}, {'country': 'South Korea', 'metric': 'total_military_manpower', 'value': 26040900}, {'country': 'Colombia', 'metric': 'total_military_manpower', 'value': 24298295}, {'country': 'Algeria', 'metric': 'total_military_manpower', 'value': 22570787}, {'country': 'Spain', 'metric': 'total_military_manpower', 'value': 21748999}, {'country': 'Kenya', 'metric': 'total_military_manpower', 'value': 21551160}, {'country': 'Argentina', 'metric': 'total_military_manpower', 'value': 20677529}, {'country': 'Saudi Arabia', 'metric': 'total_military_manpower', 'value': 19003104}, {'country': 'Uzbekistan', 'metric': 'total_military_manpower', 'value': 18990708}, {'country': 'Poland', 'metric': 'total_military_manpower', 'value': 18985692}, {'country': 'Ukraine', 'metric': 'total_military_manpower', 'value': 18187531}, {'country': 'Morocco', 'metric': 'total_military_manpower', 'value': 17946041}, {'country': 'Iraq', 'metric': 'total_military_manpower', 'value': 17675043}, {'country': 'Uganda', 'metric': 'total_military_manpower', 'value': 16756234}, {'country': 'Canada', 'metric': 'total_military_manpower', 'value': 16681770}, {'country': 'Malaysia', 'metric': 'total_military_manpower', 'value': 16245461}, {'country': 'Peru', 'metric': 'total_military_manpower', 'value': 15648120}, {'country': 'Afghanistan', 'metric': 'total_military_manpower', 'value': 15647405}, {'country': 'Venezuela', 'metric': 'total_military_manpower', 'value': 15625153}, {'country': 'Syria', 'metric': 'total_military_manpower', 'value': 15273871}, {'country': 'Nepal', 'metric': 'total_military_manpower', 'value': 15249970}, {'country': 'Ghana', 'metric': 'total_military_manpower', 'value': 14873310}, {'country': 'Mozambique', 'metric': 'total_military_manpower', 'value': 14674420}, {'country': 'Ivory Coast', 'metric': 'total_military_manpower', 'value': 12292521}, {'country': 'Taiwan', 'metric': 'total_military_manpower', 'value': 12269542}, {'country': 'Yemen', 'metric': 'total_military_manpower', 'value': 12213368}, {'country': 'Tanzania', 'metric': 'total_military_manpower', 'value': 12143182}, {'country': 'Australia', 'metric': 'total_military_manpower', 'value': 11242811}, {'country': 'Madagascar', 'metric': 'total_military_manpower', 'value': 11192031}, {'country': 'Sri Lanka', 'metric': 'total_military_manpower', 'value': 10551652}, {'country': 'Cameroon', 'metric': 'total_military_manpower', 'value': 10528476}, {'country': 'North Korea', 'metric': 'total_military_manpower', 'value': 9467520}, {'country': 'Romania', 'metric': 'total_military_manpower', 'value': 9437041}, {'country': 'Kazakhstan', 'metric': 'total_military_manpower', 'value': 9117003}, {'country': 'Chile', 'metric': 'total_military_manpower', 'value': 8959033}, {'country': 'Burkina Faso', 'metric': 'total_military_manpower', 'value': 8525614}, {'country': 'Ecuador', 'metric': 'total_military_manpower', 'value': 8422593}, {'country': 'Cambodia', 'metric': 'total_military_manpower', 'value': 8190561}, {'country': 'Netherlands', 'metric': 'total_military_manpower', 'value': 7997570}, {'country': 'Niger', 'metric': 'total_military_manpower', 'value': 7902835}, {'country': 'Guatemala', 'metric': 'total_military_manpower', 'value': 7484639}, {'country': 'Angola', 'metric': 'total_military_manpower', 'value': 7440412}, {'country': 'Zambia', 'metric': 'total_military_manpower', 'value': 7279691}, {'country': 'Senegal', 'metric': 'total_military_manpower', 'value': 7162057}, {'country': 'Chad', 'metric': 'total_military_manpower', 'value': 6873694}, {'country': 'Mali', 'metric': 'total_military_manpower', 'value': 6817088}, {'country': 'Zimbabwe', 'metric': 'total_military_manpower', 'value': 6517134}, {'country': 'South Sudan', 'metric': 'total_military_manpower', 'value': 6351857}, {'country': 'Tunisia', 'metric': 'total_military_manpower', 'value': 6024424}, {'country': 'Cuba', 'metric': 'total_military_manpower', 'value': 5921661}, {'country': 'United Arab Emirates', 'metric': 'total_military_manpower', 'value': 5818684}, {'country': 'Benin', 'metric': 'total_military_manpower', 'value': 5584880}, {'country': 'Bolivia', 'metric': 'total_military_manpower', 'value': 5417269}, {'country': 'Portugal', 'metric': 'total_military_manpower', 'value': 5319863}, {'country': 'Azerbaijan', 'metric': 'total_military_manpower', 'value': 5218617}, {'country': 'Czechia', 'metric': 'total_military_manpower', 'value': 5093808}, {'country': 'Belarus', 'metric': 'total_military_manpower', 'value': 5035769}, {'country': 'Dominican Republic', 'metric': 'total_military_manpower', 'value': 4975294}, {'country': 'Greece', 'metric': 'total_military_manpower', 'value': 4916713}, {'country': 'Belgium', 'metric': 'total_military_manpower', 'value': 4910830}, {'country': 'Tajikistan', 'metric': 'total_military_manpower', 'value': 4781269}, {'country': 'Hungary', 'metric': 'total_military_manpower', 'value': 4632200}, {'country': 'Sweden', 'metric': 'total_military_manpower', 'value': 4235934}, {'country': 'Honduras', 'metric': 'total_military_manpower', 'value': 4192843}, {'country': 'Austria', 'metric': 'total_military_manpower', 'value': 4035592}, {'country': 'Israel', 'metric': 'total_military_manpower', 'value': 3949099}, {'country': 'Singapore', 'metric': 'total_military_manpower', 'value': 3918498}, {'country': 'Switzerland', 'metric': 'total_military_manpower', 'value': 3898653}, {'country': 'Libya', 'metric': 'total_military_manpower', 'value': 3827857}, {'country': 'Paraguay', 'metric': 'total_military_manpower', 'value': 3535598}, {'country': 'Laos', 'metric': 'total_military_manpower', 'value': 3499565}, {'country': 'Jordan', 'metric': 'total_military_manpower', 'value': 3463947}, {'country': 'Nicaragua', 'metric': 'total_military_manpower', 'value': 3271705}, {'country': 'Serbia', 'metric': 'total_military_manpower', 'value': 3259584}, {'country': 'Bulgaria', 'metric': 'total_military_manpower', 'value': 3187850}, {'country': 'El Salvador', 'metric': 'total_military_manpower', 'value': 3181777}, {'country': 'Kyrgyzstan', 'metric': 'total_military_manpower', 'value': 3147772}, {'country': 'Somalia', 'metric': 'total_military_manpower', 'value': 2993973}, {'country': 'Slovakia', 'metric': 'total_military_manpower', 'value': 2837461}, {'country': 'Turkmenistan', 'metric': 'total_military_manpower', 'value': 2768681}, {'country': 'Georgia', 'metric': 'total_military_manpower', 'value': 2744538}, {'country': 'Denmark', 'metric': 'total_military_manpower', 'value': 2628180}, {'country': 'Ireland', 'metric': 'total_military_manpower', 'value': 2407392}, {'country': 'Liberia', 'metric': 'total_military_manpower', 'value': 2392390}, {'country': 'Bosnia and Herzegovina', 'metric': 'total_military_manpower', 'value': 2355176}, {'country': 'Finland', 'metric': 'total_military_manpower', 'value': 2306830}, {'country': 'Republic of the Congo', 'metric': 'total_military_manpower', 'value': 2256136}, {'country': 'Eritrea', 'metric': 'total_military_manpower', 'value': 2220385}, {'country': 'New Zealand', 'metric': 'total_military_manpower', 'value': 2219321}, {'country': 'Norway', 'metric': 'total_military_manpower', 'value': 2203893}, {'countr

In [ ]:
import pandas as pd

df = pd.DataFrame(final_result)
df.head()

         country            metric       value
0          China  total_population  1415043270
1          India  total_population  1409128296
2  United States  total_population   341963408
3      Indonesia  total_population   281562465
4       Pakistan  total_population   252363571

In [ ]:
df = df.pivot(
    index="country",
    columns="metric",
    values="value"
)

In [ ]:
df=df.reset_index()

In [ ]:
df.head()

metric,country,active_personnel,aircraft_carriers,armored_fighting_vehicles,attack_aircraft,attack_helicopters,border_coverage_km,coal_consumption_mt,coal_production_cum,coastal_patrol_craft,...,total_military_helicopters,total_military_manpower,total_naval_fleet,total_naval_fleet_tonnage_mt,total_population,total_serviceable_airports,towed_artillery,trainer_aircraft,transport_aircraft,waterway_coverage_km
0,Afghanistan,0.0,0.0,5202.0,0.0,1.0,5987.0,1545000.0,4885000.0,0.0,...,6.0,15647405.0,0.0,NaN,40121552.0,67.0,0.0,0.0,3.0,1200.0
1,Albania,6600.0,0.0,1796.0,0.0,0.0,691.0,389000.0,379000.0,19.0,...,19.0,1522479.0,19.0,NaN,3107100.0,3.0,50.0,0.0,0.0,41.0
2,Algeria,325000.0,0.0,26000.0,42.0,74.0,6734.0,167000.0,0.0,75.0,...,299.0,22570787.0,110.0,82880.0,47022473.0,85.0,483.0,87.0,63.0,0.0
3,Angola,107000.0,0.0,5500.0,12.0,15.0,5369.0,0.0,0.0,29.0,...,116.0,7440412.0,31.0,NaN,37202061.0,106.0,575.0,66.0,31.0,1300.0
4,Argentina,108000.0,0.0,21724.0,11.0,0.0,11968.0,3391000.0,1318000.0,13.0,...,94.0,20677529.0,44.0,122128.0,46994384.0,756.0,172.0,71.0,52.0,11000.0

In [ ]:
df.isnull().sum()

metric
country                                       0
active_personnel                              0
aircraft_carriers                             0
armored_fighting_vehicles                     0
attack_aircraft                               0
attack_helicopters                            0
border_coverage_km                            0
coal_consumption_mt                           0
coal_production_cum                           0
coastal_patrol_craft                          0
coastline_coverage_km                         0
corvettes                                     0
defense_budget_usd                            0
destroyers                                    0
external_debt_usd                             0
fighter_aircraft                              0
fit_for_service                               0
foreign_exchange_and_gold_reserves_usd        0
frigates                                      0
helicopter_carriers                           0
labour_force                                  0
major_ports_and_terminals                     0
mine_warfare_craft                            0
natural_gas_consumption_cum                   0
natural_gas_production_cum                    0
oil_consumption_bbl                           0
oil_production_bbl                            0
paramilitary                                  0
population_reaching_military_age_annually     0
proven_coal_reserves_cum                      0
proven_natural_gas_reserves_cum               0
proven_oil_reserves_bbl                       0
purchasing_power_parity_usd                   0
railway_coverage_km                           0
reserve_personnel                             0
roadway_coverage_km                           0
rocket_projectors                             0
self_propelled_artillery                      0
special_mission_aircraft                      0
submarines                                    0
tanker_aircraft                               0
tanks                                         0
total_land_area_sq_km                         0
total_merchant_marine_fleet                   0
total_military_aircraft                       0
total_military_helicopters                    0
total_military_manpower                       0
total_naval_fleet                             0
total_naval_fleet_tonnage_mt                 98
total_population                              0
total_serviceable_airports                    0
towed_artillery                               0
trainer_aircraft                              0
transport_aircraft                            0
waterway_coverage_km                          0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 55 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    145 non-null    object
 1   active_personnel                           145 non-null    float64
 2   aircraft_carriers                          145 non-null    float64
 3   armored_fighting_vehicles                  145 non-null    float64
 4   attack_aircraft                            145 non-null    float64
 5   attack_helicopters                         145 non-null    float64
 6   border_coverage_km                         145 non-null    float64
 7   coal_consumption_mt                        145 non-null    float64
 8   coal_production_cum                        145 non-null    float64
 9   coastal_patrol_craft                       145 non-null    float64
 10  coastline_coverage_km                      145 non-null    float64
 11  corvettes                                  145 non-null    float64
 12  defense_budget_usd                         145 non-null    float64
 13  destroyers                                 145 non-null    float64
 14  external_debt_usd                          145 non-null    float64
 15  fighter_aircraft                           145 non-null    float64
 16  fit_for_service                            145 non-null    float64
 17  foreign_exchange_and_gold_reserves_usd     145 non-null    float64
 18  frigates                                   145 non-null    float64
 19  helicopter_carriers                        145 non-null    float64
 20  labour_force                               145 non-null    float64
 21  major_ports_and_terminals                  145 non-null    float64
 22  mine_warfare_craft                         145 non-null    float64
 23  natural_gas_consumption_cum                145 non-null    float64
 24  natural_gas_production_cum                 145 non-null    float64
 25  oil_consumption_bbl                        145 non-null    float64
 26  oil_production_bbl                         145 non-null    float64
 27  paramilitary                               145 non-null    float64
 28  population_reaching_military_age_annually  145 non-null    float64
 29  proven_coal_reserves_cum                   145 non-null    float64
 30  proven_natural_gas_reserves_cum            145 non-null    float64
 31  proven_oil_reserves_bbl                    145 non-null    float64
 32  purchasing_power_parity_usd                145 non-null    float64
 33  railway_coverage_km                        145 non-null    float64
 34  reserve_personnel                          145 non-null    float64
 35  roadway_coverage_km                        145 non-null    float64
 36  rocket_projectors                          145 non-null    float64
 37  self_propelled_artillery                   145 non-null    float64
 38  special_mission_aircraft                   145 non-null    float64
 39  submarines                                 145 non-null    float64
 40  tanker_aircraft                            145 non-null    float64
 41  tanks                                      145 non-null    float64
 42  total_land_area_sq_km                      145 non-null    float64
 43  total_merchant_marine_fleet                145 non-null    float64
 44  total_military_aircraft                    145 non-null    float64
 45  total_military_helicopters                 145 non-null    float64
 46  total_military_manpower                    145 non-null    float64
 47  total_naval_fleet                          145 non-null    float64
 48  total_naval_fleet_tonnage_mt               47 non-null     float64
 49  total_population                           145 non-null    float64
 50  total_serviceable_airports                 145 non-null    float64
 51  towed_artillery                            145 non-null    float64
 52  trainer_aircraft                           145 non-null    float64
 53  transport_aircraft                         145 non-null    float64
 54  waterway_coverage_km                       145 non-null    float64
dtypes: float64(54), object(1)
memory usage: 62.4+ KB

In [ ]:
df.drop('total_naval_fleet_tonnage_mt',axis=1,inplace=True)